### ISSUE TITLE
Refactor to follow DRY

### ISSUE THREAD

**Issue by dmugtasimov** [kmmbvnr/django-fsm#103]
def can_proceed(bound_method, check_conditions=True):
        """
        Returns True if model in state allows to call bound_method
    
        Set ``check_conditions`` argument to ``False`` to skip checking
        conditions.
        """
        if not hasattr(bound_method, '_django_fsm'):
            raise TypeError('%s method is not transition' % bound_method.im_func.__name__)
    
        meta = bound_method._django_fsm
        im_self = getattr(bound_method, 'im_self', getattr(bound_method, '__self__'))
        current_state = meta.field.get_state(im_self)
    
        return meta.has_transition(current_state) and (
            not check_conditions or meta.conditions_met(im_self, current_state))
    
    
    def has_transition_perm(bound_method, user):
        """
        Returns True if model in state allows to call bound_method and user have rights on it
        """
        if not hasattr(bound_method, '_django_fsm'):
            raise TypeError('%s method is not transition' % bound_method.im_func.__name__)
    
        meta = bound_method._django_fsm
        im_self = getattr(bound_method, 'im_self', getattr(bound_method, '__self__'))
        current_state = meta.field.get_state(im_self)
    
        return (meta.has_transition(current_state)
                and meta.conditions_met(im_self, current_state)
                and meta.has_transition_perm(im_self, current_state, user))

**Comment by kmmbvnr** [comment]
Too simple to simplify more.
