### ISSUE TITLE
“Set to change state” descriptor mode

### ISSUE THREAD

**Issue by spectras** [kmmbvnr/django-fsm#105]
At the moment, FSM field descriptors work in either of two modes: protected, in which setting the state raises an exception, and unprotected, in which setting the state bypasses all transitions.

I was wondering whether an additional mode could be added, in which setting the state would trigger a transition, using `change_state` with no optional arguments. I know I can do that easily by inheriting `FSMFieldMixin` and setting a custom `descriptor_class`, but direct support by fsm would be much cleaner.

Maybe it would be sensible to make `TransitionNotAllowed` a subclass of `ValueError`.

(Great module by the way, abstracting out this common pattern comes in really handy).

**Comment by kmmbvnr** [comment]
The idea of fsm is not to set state directly at all, So unprotected is just a way not to check it by fsm, but not to avoid by end user.

Having ability to directly set the state can't be implemented, b/c you can have several transition attached to the same source-target pair  and we django-fsm will not able to select the correct one.

**Comment by kmmbvnr** [comment]
Btw - https://github.com/kmmbvnr/django-fsm/pull/68/files#diff-7b4b9604f1842ff54833d14e644e9710R127

**Comment by spectras** [comment]
Excellent point, I did not envision there could be several transitions with the same source/target pair.
Thanks a lot for answering so fast.

**Comment by kmmbvnr** [comment]
Yeah, but it's a good idea to create a simpler library than django_fsm with the state field with list of transitions and no @transition decorator over methods.
