### ISSUE TITLE
Clarify use of first parameter to @transition

### ISSUE THREAD

**Issue by orf** [kmmbvnr/django-fsm#109]
Hey there! This library is so awesome, thank you for your work on it. I'm working on a project that uses [Django-hvad](https://github.com/KristianOellegaard/django-hvad) for translations, and each of our translated models needs to have an individual FSMIntegerField. Currently our code looks like this:

```python
class SomeMixin(ConcurrentTransitionMixin):
    qa_state = FSMIntegerField(default=QAState.DRAFT, choices=QAState.choices(), protected=True)

    @transition(qa_state, source=(QAState.DRAFT, QAState.TECH_QA_AUTHOR_UPDATES), target=QAState.TECH_QA)
    def send_for_tech_qa(self, user: User):
        do_something()
```

However `hvad` defines translations like this:

```python
translations = TranslatedFields(
   title=models.CharField(...)
)
```

This causes issues because the `@transition` decorator takes a field as a first argument (which isn't available, because it's inside the TranslatedFields 'field'. The first parameter goes into the `FSMMeta`'s `field` attribute, but it doesn't seem to be used anywhere.

So my question is can the `@transition` decorator accept a string field name as the first argument rather than an actual field instance? I've done some playing and nothing seems to break, but I'm curious as to if this is a good idea or not.

**Comment by kmmbvnr** [comment]
First of all, please don't use issue tracker as q&a website.

Second. you should try first, before asking,

And third, i don't think that will works.

**Comment by orf** [comment]
Woah, ok, glitter looked dead and this is actually an issue. I have tried, and it does work, which begs the question why the `field` parameter is needed at all. Seeing as it's not used by the code that makes it an issue, no?

Even so I don't feel comfortable using it in case you decide to use it in a later update, perhaps a nice feature would be to specify the field name as a string. Bam, double whammy, a issue and a feature request all in one.

**Comment by kmmbvnr** [comment]
No. You are wrong about that field is not used.
