### ISSUE TITLE
How to give object level permissions

### ISSUE THREAD

**Issue by parijathakumar** [kmmbvnr/django-fsm#114]
" permission accepts a permission string, or callable that expects user argument and returns True if user can perform the transition."

How to give object level permissions ? Example, I've a 'Task' model with 'status' as FSM field. The 'status' can be 'Open' or 'Closed'. There is another TaskUser model with users and roles. I should be able to add a 'close' transition method with permission to the users who have 'admin' role for the specific task.

**Comment by kmmbvnr** [comment]
Please don't use issue tracker as Q&Q website.

Here is http://stackoverflow.com/ for that.

**Comment by parijathakumar** [comment]
OK. Thank you.
