### ISSUE TITLE
Passing args/kwargs to conditions

### ISSUE THREAD

**Issue by lwm** [kmmbvnr/django-fsm#117]
When I pass a `conditions=[x]` to the transition decorator, I'd like those condition functions to have access to the `*args` and `**kwargs` that I pass to the transition function. This would make this feature *much* more useful - transition functions often accept parameters not on the model instance purely for the purpose of validation.

For example, if I have the following:

```
@transition(field=x, source=y, target=z, conditions=[myfunc])
def publish(self, arg1, kwarg1=42):
    ...
```

And then, in the `myfunc` definition, I'd like to use `arg1` and `kwarg1` as well.

```
def myfunc(instance, *args, **kwargs):
    arg1 = args[0]
    kwarg1 = kwargs.get('kwarg1')
    ...
```

I've had a go at it (see PR coming soon) but it wasn't really a good solution. I'd like to see what you think in any case :+1:

**Comment by kmmbvnr** [comment]
Do you have real live usecase for that?

**Comment by lwm** [comment]
Sure. 

I have a `Task` model which has a state transition, `assign`. A call to `assign` would look like `task.assign(user)`. I need to check in my condition function if the `user` has an affiliation with the creator of the task. 

This can't be achieved with only access to the `Task` instance because `assignee` is passed as an arg, for the purpose of validation.

**Comment by kmmbvnr** [comment]
понедельник, 15 февраля 2016 г. пользователь Luke Murphy написал:

> Sure. Со из мг лоз тд бхакти.
>
I have a Task model which has a state transition, assign. A call to assign
> would look like task.assign(user). I need to check in my condition
> function if the user has an affiliation with the creator of the task.
>
> This can't be achieved with only access to the Task instance because
> assignee is passed as an arg, for the purpose of validation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmmbvnr/django-fsm/issues/117#issuecomment-184231859>.
>


-- 

Yours sincerely,
Mikhail Podgurskiy,
Omsk, Russia.

E-Mail: kmmbvnr@gmail.com
Mobile Phone: +79609900996
Skype: mpodgurs

**Comment by kmmbvnr** [comment]
I feels like it should be in FAQ.

Over 6 years of the django-fsm life, [pull]requests about kwargs on conditions was proposed several times (ex: https://github.com/kmmbvnr/django-fsm/pull/35)

And was not merged for several reasons.

The main problem that the only real-life use case is to add user permission check on model level. This solution have several drawbacks.

- Obviously this is violation of M-V-T separation. Permissions check should be performed on the View layer. Elsewhere you could have a bad situations, like in a management commands or celery tasks, where you have no specific user, but still would like to change model state.

- Generally `TransitionNotAllowed` is the bad exception in case of failing permission check, like task.assign()

- And finally, it makes unusable methods like `get_available_transitions`

So, instead i've added to django-fsm  shortcut to associate views and permissions -   https://github.com/kmmbvnr/django-fsm#permissions that simplifies permissions checking code on a view layer, where you can decide on a right action, and right fallback on error. Modern django class-based-views makes really easy to create reusable mixins, to avoid code repetition.

And at the last, the ultimate solution for all of this problems, is to have a separate workflow layer, that extracts workflow logic out of views and models. That's implemented in the [django-viewflow](https://github.com/viewflow/viewflow) library

**Comment by lwm** [comment]
Woops, forgot to search. :+1:
