### ISSUE TITLE
allow multiple sources and multiple targets at one transition

### ISSUE THREAD

**Issue by Chitrank-Dixit** [kmmbvnr/django-fsm#122]
Hello Developers,

I found django-fsm and all of my problems got solved. I am able to use it according to my product requirement and able to change the status of my product from placed to confirm and so on. Now I have lots of status from there the order can be cancelled. So I was looking to specify multiple sources like

```
@transition(field=status, source=[OrderStatusChoices.PLACED, OrderStatusChoices.CONFIRM, OrderStatusChoices.QUALITY_CHECKED], target=OrderStatusChoices.CANCELLED )
    def order_cancelled_by_user(self):
        pass
```

It also applies to Target. I am in need to specify this kind of transition otherwise there would be lots of redundancy in my code that I want to eliminate to keep the code clean and readable.

**Comment by kmmbvnr** [comment]
You can use multiple source - https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/tests/test_basic_transitions.py#L27

Or several transition decorator to specify diferrent traget depends on source:

https://github.com/kmmbvnr/django-fsm/blob/master/tests/testapp/tests/test_multidecorators.py#L12

**Comment by diegoponciano** [comment]
@kmmbvnr is there a way to know from which source the transition is comming? inside the annotated model function
