### ISSUE TITLE
FSMIntegerField: Drawing Graph

### ISSUE THREAD

**Issue by vanhoofseppe** [kmmbvnr/django-fsm#124]
Can not generate graph because of the integer
- graph_transitions.py:86 label=label to label=str(label)
- graph_transitions.py:88 label=label to label=str(label)

**Comment by kmmbvnr** [comment]
seems already fixed in master 
https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/management/commands/graph_transitions.py#L49
