### ISSUE TITLE
Based on different transition condition failure, can we return multiple error message

### ISSUE THREAD

**Issue by ikbhal-blackbuck** [kmmbvnr/django-fsm#127]
Lets there is transition from "Order Processing" to "Order Accepted" on conditions = ['condition', 'condition2', 'condition3'..]

if condition1 fails -> can i get any error message, 
so that i can retrieve that message return in the response.

Similarly for failed conditions, multiple error message, error codes

**Comment by kmmbvnr** [comment]
Yep, this could be a nice feature

**Comment by gergelypolonkai** [comment]
How about making it possible for conditions to be tuples? Ie. if it's a callable, handle it the current way; if it's a tuple, treat the first element as the condition callable, the second one as the message, and the (probably optional) third as an error code; this latter is to allow for possibly translated messages and also a programmatically easy method for error handling.

**Comment by gergelypolonkai** [comment]
Now that I see how conditions are implemented, this doesn’t look like *that* trivial. If no one else, I’m in for patching up a prototype for this.

**Comment by kmmbvnr** [comment]
I'm thinking about to use docstrings instead of tuples for conditions. 

Ex:  https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L41

We can apply translation to the extracted docstring. Elsewhere it could be hard to reuse conditions in several places and the @transition definition could looks a bit fat.

**Comment by gergelypolonkai** [comment]
Using docstrings for this purpose sounds just wrong to me, especially as I document my model functions there (to be used by Sphinx).

**Comment by kmmbvnr** [comment]
I think the docstrings is the only way to proceed further.

The error message could be marked with Shinx-like keyword.

ex:

    def all_leading_cancelled(self):
        """
        Checks that all children tasks are canceled

       :error_message: Some leading tasks are not canceled 
        """
        return False

If the keyword is present it should be used as the error message, elsewhere the whole docstring.

**Comment by gergelypolonkai** [comment]
And how about lambdas? They are hard, if at all possible to document this way.

**Comment by dangusev** [comment]
What about returning the tuple with (False, 'error') in case of negative outcome? This way seems to me quite transparent and easy to implement. Sometimes one function can make several checks and you may need to return different messages based on failed check.

**Comment by gergelypolonkai** [comment]
That sounds more reasonable, yes, and maybe also easier to implement.

**Comment by rpkilby** [comment]
Return a tuple is a better option. Doc strings don't allow you to customize the error message. eg, 

```py
def some_condition():
    """
    :error: You have screwed up
    """
    return False

# vs
def some_condition():
    errors = [...]
    return (False, 'You have screwed up in all of these various ways: %s' % ', '.join(errors))
```

**Comment by kmmbvnr** [comment]
I think the conditions functions that could return a boolean or tuple and with possibility to error message customization is to complicated solution.

Generally i didn't see any python package that have same sort of error reporting over  return tuple with error message.

If you have 2 different cases, you can have 2 different conditions, each with explicit and specific error message.

**Comment by rpkilby** [comment]
Counter example:
```py
def no_outstanding_orders(self):
    outstanding = self.order_set.filter(complete=False)
    if outstanding.empty():
        return True
    return False, "You have %s outstanding orders" % outstanding.count()
```

**Comment by dangusev** [comment]
It could be useful if you want to check multiple conditions in one function because of some performance reasons (e.g. complex db queries).

**Comment by rpkilby** [comment]
Also, I'm not strongly advocating the above syntax. However, I do not think multiple conditions satisfies all cases. An alternative...
```py
def get_outstanding_errors_message(self):
    ...

def no_outstanding_errors(self):
    ...

# takes callable or string
no_outstanding_errors.error_message = get_outstanding_errors_message
```

**Comment by kmmbvnr** [comment]
I think yo guys tries to do too much on the model layer.
