### ISSUE TITLE
Why is there no on_error callback?

### ISSUE THREAD

**Issue by bazinga012** [kmmbvnr/django-fsm#131]
Hi,
I want to execute some code on transition failure what are my options??
FSM does provide a way to move object to some errored state but why does it not provide a callback function(or signal) for it??

**Comment by kmmbvnr** [comment]
django_fsm always reraising the exceiption, so you can just handle it in your code

https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/__init__.py#L331
