### ISSUE TITLE
Signal expose field name

### ISSUE THREAD

**Issue by scotta** [kmmbvnr/django-fsm#133]
When a model has multiple states it would be beneficial to know which field was modified.
I currently use 

`getattr(sender, name)._django_fsm.field.name`

which in theory could break in future releases.

**Comment by kmmbvnr** [comment]
i think it's ok to pass the field itself

`meta.field` need to be added here 
https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/__init__.py#L309

**Comment by kmmbvnr** [comment]
btw, i'm quire impressed by count of reports related to the signals. I'm personally never used signals with django-fsm over all 6 years of library development.

What kind of problem you are trying to solve with signals? Generally, it could be useful only in case of 3d party app integration.

**Comment by hugorodgerbrown** [comment]
Pitching in here - we use the signals to audit state transitions, and use this for various reasons - tracking the interval between transitions, tracking who has made the transition, compliance reasons. Having access to the field name would be useful as we are starting to use models with multiple states.

```python

@receiver(post_transition, dispatch_uid="state_transition")
def on_state_transition(sender, **kwargs):
    """Audit django_fsm state transitions."""
    instance = kwargs.get('instance')
    source = kwargs.get('source')
    target = kwargs.get('target')
    try:
        transition = StateTransition(
            subject=instance,
            state_before=source,
            state_after=target,
            transitioned_by=getattr(instance, 'transitioned_by', None)
        )
        transition.save()
    except Exception as e:
        logger.exception(
            u"There was a problem saving a StateTransition, "
            "so it has been written to the log instead. (%s: %s)",
            type(e), e
        )
        logger.info(
            "%s (%s) transitioned from '%s' to '%s'",
            sender.__name__, instance.id, source, target
        )

**Comment by kmmbvnr** [comment]
PRs are welcome
