### ISSUE TITLE
Optional permission check upon execution

### ISSUE THREAD

**Issue by gergelypolonkai** [kmmbvnr/django-fsm#134]
Based on past requests I’m not really sure this is a valid case due to the lack of MVT separation, but what if you do it conditionally?

E.g. add a `permcheck_user` parameter to `@transition()`, defaulting to `None`, and if it is defined, the User specified in the kwarg specified by `permcheck_user` should be checked against the permission of the Transition.

It seems others want such a feature. It’s not too hard to do it with a decorator **around** @transition, but implementing it in @transition seems more appropriate to me. Also, @transition already puts some view logic into the models, so why not extend it a bit?

**Comment by kmmbvnr** [comment]
Answered many times already https://github.com/kmmbvnr/django-fsm/issues/117#issuecomment-184277590
