### ISSUE TITLE
Django base versions

### ISSUE THREAD

**Issue by vyscond** [kmmbvnr/django-fsm#135]
Since there is no explicit text saying anything about django version i will assume it cover any version right? If this is not correct could you please put a table of it? And even if it's the correct assumption can you please put it explicit?

Great project btw. Cheers.

**Comment by kmmbvnr** [comment]
list of currently supported python/django versions could be found in the tox file - https://github.com/kmmbvnr/django-fsm/blob/master/tox.ini
