### ISSUE TITLE
Defining transitions in subclasses.

### ISSUE THREAD

**Issue by AndySun25** [kmmbvnr/django-fsm#138]
Hi there.
Assuming I have an inheritance structure as follows where I would like to override or declare a new transition method on the subclass (in my case I would actually like to change the transition source and target states as well), how can I go about referencing the parent model's state field?

```python
class Post(models.Model):
    state = FSMField(...)

    @transition(field=state, source...)
    def publish(self):
        pass

class DifferentPost(Post):
    @transition(field=??, source...)
    def publish(self):
        pass
```

I've tried the following
```python
@transition(field=Post.state, ...)
```
but that ended up throwing [this](https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/__init__.py#L225) error.

**Comment by kmmbvnr** [comment]
You can use string references - https://github.com/kmmbvnr/django-fsm/blob/master/tests/testapp/tests/test_string_field_parameter.py#L13
