### ISSUE TITLE
How can I get what conditions fails for a given transition?

### ISSUE THREAD

**Issue by rpalacios** [kmmbvnr/django-fsm#140]
When I call `get_available_FIELD_transitions`, it will return all available transitions that comply or satisfy given conditions, if they have it.

I want to know how to get transitions that don't satisfy the transition's conditions.

I want to do this in order to notify user what transition are available, and what conditions will be available when conditions get satified.

There is a way to do this?

Thanks in advance.

**Comment by kmmbvnr** [comment]
You can get get_all_FIELD_transitions and exclude available
