### ISSUE TITLE
target parameter of post_transition signal should be the resulting state

### ISSUE THREAD

**Issue by kbussell** [kmmbvnr/django-fsm#151]
If the target of the transition is `GET_STATE` or `RETURN_VALUE`, `post_transition` gets the `State` object instead of the resulting state.

**Comment by kmmbvnr** [comment]
Thanks for the fix.

Btw, could you show for what purpose do you use signals? For all 6 years of django-fsm development and usage I newer have to use signals in mine projects.

**Comment by kbussell** [comment]
We sometimes trigger notifications or activity stream object creation on state transitions. Examples:
• when an e-signature document object changes state to signed, trigger an email notification 
• when an application changes state to declined, send a Slack message to someone
