### ISSUE TITLE
django-model-utils compatibility

### ISSUE THREAD

**Issue by brawaga** [kmmbvnr/django-fsm#156]
We had an issue when trying django_fsm and FieldTracker from django-model-utils on querysets with deferred fields.
Investigation shown that FSMFieldDescriptor.__get__ method has invalid behaviour when model class itself is being accessed to get the attr corresponding to the FSM field defined on the model.
Valid descriptor should return field instance for model class and value for model instance, whereas FSM raises an exception and after I add FSM field I am no more able to iterate model class attributes safely.
Moreover, FSM field should have field_name attribute.
Look forward for corrections, thanks in advance and best regards.

**Comment by kmmbvnr** [comment]
Pull requests are always welcome

**Comment by brawaga** [comment]
Thanks, I made a pull request. But, actually, issue persists without model-utils usage. Just try to access the FSM field via getattr'ing model class. Expected behaviour is to get field instance, but you will get an exception raised.

**Comment by brawaga** [comment]
I can nothing to say in details what's wrong with deferred querysets, no noticeable investigation done, but you can just take in mind something could be wrong with.

**Comment by kmmbvnr** [comment]
You can't getattr for django model fields. Read the docs about django meta api
