### ISSUE TITLE
Automatically add obj.<state_field>_is_<state> property

### ISSUE THREAD

**Issue by hugorodgerbrown** [kmmbvnr/django-fsm#166]
We have a lot of state checking code:

```python
if obj.state == 'complete':
    ...
```

To tidy this up we have a lot of helper properties on the models:

```python
@property
def is_complete(self):
    return self.state == 'complete'
```

It would be really nice if there were a way to auto-magically wire these up, like the Django `get_FOO_display` [methods](https://github.com/django/django/blob/master/django/db/models/fields/__init__.py#L686):

```python
if obj.state_is_complete:
    ...
```

**Comment by kmmbvnr** [comment]
Consider to use `can_proceed()` method instead.
