### ISSUE TITLE
calling getattr() on FSM field returns a string, not native type

### ISSUE THREAD

**Issue by laurentS** [kmmbvnr/django-fsm#170]
This issue came about when integrating `django-fsm` and `django-rest-framework`.

When calling `getattr(myModelInstance, 'state')` the result is a string, which is not consistent with other Django field types.

Given the model below:

```
    class Example(models.Model):
        fkfield = models.ForeignKey(SomeOtherModel)
        timestamp = models.DateTime(...)
        state = FSMIntegerField(choices=...)
```

calling `getattr()` returns the native type, ie:
`getattr(myexample, 'fkfield')` returns `<SomeOtherField: someValue>`
`getattr(myexample, 'timestamp')` returns `datetime.date(2016, 11, 22)`
but
`getattr(myexample, 'state') returns a string, which makes dealing with the object harder, because of the inconsistency with other fields. I am using an `Enum` for the various states, which causes trouble.

Shouldn't `getattr` return the native type, like for other field types?

**Comment by kmmbvnr** [comment]
I don't think that's it's true. elsewhere the following test would fail - https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/tests/test_integer_field.py#L30

Probably you just assign the string in your code.
