### ISSUE TITLE
FSMKeyField hides related model

### ISSUE THREAD

**Issue by pembo13** [kmmbvnr/django-fsm#181]
I have

```
class CampaignStatus(models.Model):

	name = models.CharField(max_length=50, primary_key=True)
	label = models.CharField(max_length=50, unique=True)

class Campaign(models.Model):
	name = models.CharField(blank=True, max_length=200)
	status = FSMKeyField('CampaignStatus', models.PROTECT, related_name='campaigns', default='new')
```

And `Campaign.objects.first().status` returns a string consistently.

Also, is that really the correct way to define a default for a ForeignKey subclass?

**Comment by kmmbvnr** [comment]
THat's by design https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/tests/test_key_field.py

**Comment by pembo13** [comment]
So then it's just not possible to get the underlying model? I have additional fields on the model that I want to access.

**Comment by kmmbvnr** [comment]
Yep, generally, i agree that the implementation is far from the ideal.

But I have no further plans to work on it.
