### ISSUE TITLE
Support for `is_[state]` methods in model.

### ISSUE THREAD

**Issue by ibrahim12** [kmmbvnr/django-fsm#182]
- What about adding support for current state checking methods ?

Lets say, states are 'active', 'inactive', 'pending'.
Model will have, 'is_active()', 'is_inacitve()', 'is_pending()' methods to check against current state.

`FSMFieldMixin` can add this methods by iterating through choices.

I can send a pull request.

**Comment by kmmbvnr** [comment]
It looks that yhis would be problematic to implement with FSMKeyField and FSMIntegerField, ex: 'is_0' is not helpfull.

And I'm sorry, I don't see the value. `model.state == STATUS.PENDING` works fine.
