### ISSUE TITLE
get_available_FIELD_transitions doesn't seem to work anymore...

### ISSUE THREAD

**Issue by bogdanpetrea** [kmmbvnr/django-fsm#183]
...at least on Django 1.11.

From a glance this is what might be wrong:
`FSMMeta.add_transition` adds `Transition` objects into the the `transitions` attribute of the `FSMMeta` object.
The `get_available_FIELD_transitions` method seems to get transitions directly from the field's `transitions` attribute (`FSMMeta.field.transitions`).

Maybe there was some magic supposed to happen, which broke in Django 1.11. Or it is simply broken, I can't really tell.

**Comment by kmmbvnr** [comment]
Can't reproduce https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/tests/test_basic_transitions.py#L147
