### ISSUE TITLE
Transition condition methods are resolved at declaration time instead of dynamically

### ISSUE THREAD

**Issue by Bartvds** [kmmbvnr/django-fsm#184]
If we extend a class that has some transition conditions we cannot override the condition model methods because they are resolved at declaration time instead of looked up at the actual instance. (This also prohibits monkey-patching).

It would be cool if the condition parameter would accept strings with the model methods names instead of direct references to method declarations.

The use case is re-using and customizing a moderately complex state flow. We can workaround most issues with some boilerplate but it gets very crufty quickly.

**Comment by kmmbvnr** [comment]
In-Model fsm approach has obvious limitations.

For managing complex flow, you can take a look to the django-viewflow.
