### ISSUE TITLE
Add detail attribute to TransitionNotAllowed

### ISSUE THREAD

**Issue by mattjegan** [kmmbvnr/django-fsm#190]
# Problem

Currently `TransitionNotAllowed` takes an object, a method, and whatever other arguments. In the case of `FSMFieldMixin.change_state` it takes some string detailing the error. E.g:

```python
if not meta.has_transition(current_state):
    raise TransitionNotAllowed(
        "Can't switch from state '{0}' using method '{1}'".format(current_state, method_name),
        object=instance, method=method)
```

For users that want to use this message in further exception classes or other messages there needs to be a nice interface for getting this string. Currently, the process is:

```python
except TransitionNotAllowed as e:
    raise YourCustomException(detail=e.args[0])
```

# Proposed Solution

I propose that `TransitionNotAllowed` expose a `detail` or `message` attribute that can be called and save the user from having to look through the source code or debugging a potential `KeyError`.

**Comment by mattjegan** [comment]
@kmmbvnr I can get a PR up for this if you'd like?

**Comment by lincolwn** [comment]
@kmmbvnr I thought in something like this, but with one property in `Transition` called `exceptions_message` where this is a dict with all messages to not allowed state. Eg.
```python
@transition(field=state, source='pending', target='paid', exceptions_message=PAY_MESSAGES)
def pay(self):
    pass
```
where,  `PAY_MESSAGES` will be a dict with all messages to target state not allowed. something like this:
```python
PAY_MESSAGES = {
      'paid' : 'this order was paid'
}
```
Whether `state` is `paid` and the user calls `pay` method again `TransitionNotAllowed` will be raised with message `this order was paid`.
Whether `exceptions_message` isn't defined, the actual message to `TransitionNotAllowed` will be defined to this.

To solve this, I forked your repository and I implemented it. If you want, I can get a Pull Request up for this.

**Comment by mattjegan** [comment]
@lincolwn if you want to fork this branch that could be a good option for continuing into your `exception_message` feature.

**Comment by kmmbvnr** [comment]
You don't need to have `e.args[0]` just use `str(e)`  if you need exception text representation.

But generally, it looks that you misuse django-fsm and move to much logic to the model side. Prerequisites should be checked in the controller. The exceptions should not happen as part of a usual web application process, just in case of the programmer mistake.

**Comment by lincolwn** [comment]
About usage of text representation of Exception, I already use exactly how you saw. `str(e)` instead `e.args[0]`.

But I don't agree with your second sentence, but I understand that. Anyway I appreciate your feedback. django-fsm is very interesting.

**Comment by mattjegan** [comment]
Alrighty, thanks for the explanation @kmmbvnr

**Comment by ulgens** [comment]
If anyone finds this issue in 2026+, it is currently being fixed in the fork: https://github.com/django-commons/django-fsm-2/pull/98

Also, the current "completed" status is misleading.
