### ISSUE TITLE
Maintaining this project

### ISSUE THREAD

**Issue by mattjegan** [kmmbvnr/django-fsm#193]
Hi @kmmbvnr, 

I've noticed that this repo has quite a few issues/PRs that could be resolved with more maintainer time. I wanted to offer myself up as a maintainer if needed, otherwise perhaps moving this to and org/fork could work well for the project? Feel free to let me know your thoughts.

Kind Regards,
    Matt

**Comment by kmmbvnr** [comment]
Thank you, but the django-fsm is the pretty small library, and I can maintain but myself. I do several releases per year, probably the next one would be target to support django 2.0
