### ISSUE TITLE
KeyError: 'status'

### ISSUE THREAD

**Issue by maltitco** [kmmbvnr/django-fsm#197]
My URL:

`url(r'^pending', WorkflowMixin.pending, name='pending'),`

Providing direct to the:

    @transition(field='status', source=['*'], target='pending')
    def pending(self):

But I receive:

`KeyError: 'status'`

**Comment by kmmbvnr** [comment]
I don't think that I can help here. 

`WorkflowMixin` is not a part of django-fsm
