### ISSUE TITLE
Python 3.6.3 - 'str' object has no attribute 'change_state'

### ISSUE THREAD

**Issue by maltitco** [kmmbvnr/django-fsm#198]
Class

    def get_urls(self):
        urlpatterns = [
            url(r'^pending', self.pending, name='pending'),
        ]
        return urlpatterns

    @transition(field='status', source=['*'], target='pending')
    def pending(cls):

Returning:
 
'str' object has no attribute 'change_state'

.pyenv/versions/3.6.3/envs/DS012x669/src/django-fsm/django_fsm/__init__.py in _change_state
return fsm_meta.field.change_state(instance, func, *args, **kwargs)

**Comment by kmmbvnr** [comment]
Looks like you don't understand how Django and django-material works. I would recommend to start with django tutorial first and learn more about MVT. Next you can read django-material docs.
