### ISSUE TITLE
FSMIntegerField transition fails when target state value is 0

### ISSUE THREAD

**Issue by lucacorti** [kmmbvnr/django-fsm#76]
I spent some time debugging a state transition issue where everything seemed to b correct, except the state is not updated after executing the handler.

It seems the issue is with the target state value being 0. In this case the state transition is not performed. Changing the target state value to anything different than 0 fixes this.

Is this expected behavior? Looks like a bug to me.

**Comment by kmmbvnr** [comment]
I should upgrade to latest version - https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/__init__.py#L297

**Comment by lucacorti** [comment]
indeed thanks, missed the release
