### ISSUE TITLE
Is it possible to use a FSMKeyField with a model that has an ordinary primary key?

### ISSUE THREAD

**Issue by dalberto** [kmmbvnr/django-fsm#78]
Specifically, the model does not have a CharField as the primary key, it uses Django's default integer field.

**Comment by kmmbvnr** [comment]
Here are the examples of usage FsmKeyField https://github.com/kmmbvnr/django-fsm/blob/master/django_fsm/tests/test_key_field.py

**Comment by dalberto** [comment]
Thanks!
