### ISSUE TITLE
Re-add save parameter to @transition decorator as a feature

### ISSUE THREAD

**Issue by zenefitsbob** [kmmbvnr/django-fsm#79]
I looked through the history and it looks like this used to be a feature.  Why was it removed?  I would like to use something like this for my own project.

```@transition(... save=True)```

Thanks for providing a nice library for me to use! :)

**Comment by kmmbvnr** [comment]
There are no advantages of having that inside transition decorator.

Just call .save() explicitly.

**Comment by zenefitsbob** [comment]
The advantage is more concise code:

```post.publish()```

Instead of:

```
post.publish()
post.save()
```

Am I missing something?

**Comment by kmmbvnr** [comment]
Concise is not an advantage.

Without explicit save you have no information is model saved or not, till take a look to models.py file.
This also makes hard to implement generic actions (it would save things twice)

**Comment by tachang** [comment]
I found it pretty useful though because sometimes I am in the shell and need to transition an element. Also I sometimes forget to save but I know I really want to transition a model.

**Comment by variable** [comment]
```
class Cart(TimestampModel):
    class STATE(object):
        NEW = 'new'
        LOCKED = 'locked'

    state = FSMField(default=STATE.NEW)

    @property
    def total(self):
        return sum(item.total for item in self.items.all())

    def create_order(self, data={}):
        assert self.items.count()
        # locks the cart itself and save state
        # https://github.com/kmmbvnr/django-fsm/issues/79
        self.lock()
        self.save()
        order = Order.objects.create(cart=self, total=self.total, data=data)
        return order

    @transition(field=state, source=STATE.NEW, target=STATE.LOCKED)
    def lock(self):
        # https://github.com/kmmbvnr/django-fsm/issues/79
        # would have been nice if this feature is accepted
        # so we don't have to have a dummy function just to change state...
        pass
```
if we have the save param, I can use do 

@transition(field=state, source=STATE.NEW, target=STATE.LOCKED)
def create_order(self, data={}):
        assert self.items.count()
        order = Order.objects.create(cart=self, total=self.total, data=data)
        return order

**Comment by kmmbvnr** [comment]
If I'll have a time to few more BSD licensed code, the next version of django-fsm would set state before function entry, like I did in the viewflow - https://github.com/viewflow/viewflow/blob/master/viewflow/fsm.py#L165

That would allow writing just 

```python
@transition(field=state, source=STATE.NEW, target=STATE.LOCKED)
def lock(self):
    this.save()
```

**Comment by oxalorg** [comment]
> the next version of django-fsm would set state before function entry

@kmmbvnr Thank you for everything, but was this implemented? Can we use `self.save()` inside the transition function?

**Comment by kmmbvnr** [comment]
@oxalorg i'm working on new version of viewflow that would contain new version of state management. The main difference that fsm became decoupled from django models and composition used to make it plays together


no ETA on release though (

![Wrapping Django Models — Viewflow  low code development platform](https://user-images.githubusercontent.com/282529/80775482-92504e80-8b81-11ea-80dc-ebbbe487069e.png)
