### ISSUE TITLE
Ugly text formatting on PyPI

### ISSUE THREAD

**Issue by jrief** [kmmbvnr/django-fsm#80]
You use a ``README.md`` file, which is good. PyPI however expects text in RST format. I also do this, but in my projects ``setup.py`` I added this line

```
def read(fname):
    readme_file = os.path.join(os.path.dirname(__file__), fname)
    return os.popen('[ -x "$(which pandoc 2>/dev/null)" ] && pandoc -t rst {0} || cat {0}'.format(readme_file)).read()

setup(
    ...
    long_description=read('README.md'),
    ...
)
```

Of course you have to [install pandoc](http://pandoc.org/installing), but thats worth the trouble.

Have a look here: https://pypi.python.org/pypi/django-angular , it is generated by pandoc.

**Comment by kmmbvnr** [comment]
Thank you for noticing the pandoc. I used for one time conversion
