### ISSUE TITLE
translatable transition name

### ISSUE THREAD

**Issue by jrief** [kmmbvnr/django-fsm#87]
Wouldn't it make sense to allow something such as:
```
@transition(..., name=_("translatable transitionname"))
```
and only if name is missing, then fall back to ``transition.method.__name__``

In **django-fsm-admin** this name then could be used in multilingual environments. Currently the name is derived from the method name, which does not always give satisfying results.

**Comment by kmmbvnr** [comment]
django-fsm-admin is a trap anyway. You could simply implement basic cases, but as soon as you will need an additional users input you will be bumped.

As soon as workflow goes beyond model internal state consistence checking to user interface, it's should be implemented in a external layer. I suggest you to take a look to my next library for doing this - https://github.com/viewflow/viewflow 



For the this specific case, I think django-fsm-admin could simply call `gettext(transition.method.__name__)` to achieve requested functionality

**Comment by jrief** [comment]
Adding a commercially licensed dependency to an MIT-licensed projects, is an absolute NO-GO.

**Comment by iXioN** [comment]
+1, this feature would be amazing and solve my biggest pb with this lib

**Comment by jrief** [comment]
@kmmbvnr as I already said on another issue, adding a dependency (from a BSD licensed library) to a commercially licensed requirement is an absolute no-go.
Therefore, if you intent to drop support for django-fsm, I'm willing to take its ownership. [django-shop](https://github.com/awesto/django-shop/) relies heavily on this FSM and I'm really glad for this library.

@iXioN btw. You may look at django-shop's implementation how I handled the FSM transition translations there.

**Comment by kmmbvnr** [comment]
There ia no plans to dtop django-fsm support

**Comment by iXioN** [comment]
Hi, thanks for your reply, 
I manage this by setting the translation as custom option of the transition and calling transition.custom.name

It works pretty well for those how want translated transition name easily.
