### ISSUE TITLE
protected=True does not work with django's refresh_from_db

### ISSUE THREAD

**Issue by karyon** [kmmbvnr/django-fsm#89]
when calling [refresh_from_db](https://docs.djangoproject.com/en/1.8/ref/models/instances/#django.db.models.Model.refresh_from_db) on a model that has an FSMField with protected=True, i get the following trace:

```
Traceback (most recent call last):
  File "/vagrant/evap/staff/tests.py", line 284, in test_has_enough_questionnaires
    course.refresh_from_db()
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 627, in refresh_from_db
    setattr(self, field.attname, getattr(db_instance, field.attname))
  File "/usr/local/lib/python3.4/dist-packages/django_fsm/__init__.py", line 210, in __set__
    raise AttributeError('Direct {0} modification is not allowed'.format(self.field.name))
AttributeError: Direct state modification is not allowed
```

in case you can't fix that at all with reasonably clean code, this might at least be worth a note in the docs.

**Comment by kmmbvnr** [comment]
Yeah, please send pull request for doc

**Comment by karyon** [comment]
okay... might take a few days though.

**Comment by marksweb** [comment]
Can anything be done to get around this? I've got a Django 1.10 project with an audit logging application which uses `refresh_from_db` to show changes to objects.

It'd be nice to get a workaround rather than drop logging of models that use fsm

**Comment by mmoravcik** [comment]
You could rewrite the following

`my_obj.refresh_from_db()`

as

`my_obj = MyObject.objects.get(pk=my_obj.pk)`

**Comment by jmfederico** [comment]
How about:

```python
    def refresh_from_db(self, using=None, fields=None):
        """Reload instance from database."""
        protected = []
        for field in self._meta.get_fields():
            if getattr(field, "protected", False):
                protected.append(field)
                field.protected = False
        super().refresh_from_db(using=using, fields=fields)
        for field in protected:
            field.protected = True
```
