### ISSUE TITLE
conditions do not work with boolean properties

### ISSUE THREAD

**Issue by karyon** [kmmbvnr/django-fsm#90]
the `conditions` parameter currently must be a list of callables, that take a model instance as argument.

suppose the model has a boolean property, called `is_happy`. to make `is_happy` a condition for some transition, i would have to write some method `is_happy_func(self): return self.is_happy` or put some lambda into the conditions, which doesn't look cool.

the same problem arises when the model has a lot of functions that are `@property`s, e.g. because the project guidelines say that all methods that begin with `is_`, `has_` or `can_` should be properties (like in my case).

in case the current syntax does not work: one approach would be to allow strings in the conditions list that are used to "look up" properties on the model instance. that might be a bit weird at first sight but django uses such string parameters extensively e.g. in the QuerySet API, so django-fsm users should be familiar with that.

**Comment by kmmbvnr** [comment]
What is the example of  QuerySet API that uses string as parameters?

**Comment by karyon** [comment]
there's a lot of that, e.g. the Count object, order_by, select_related and prefetch_related, values[_list], defer and only... basically half of the queryset's methods.

...you're right, the lambda doesn't look too bad. still, real support for properties would be even more cool.

**Comment by kmmbvnr** [comment]
Mm, yep, you are right. I didn't thought about string reference to fields. 

But using strings references - that's why django ORM frequently called un-pythonic.

What is your opinion about introducing "magic" this object, like i did it in the viewflow library - https://github.com/viewflow/viewflow/blob/master/viewflow/flow/base.py#L10

This makes condition referencies looks like 

     @transition(..., conditions=[this.is_happy]
     def method(self):
         pass

This will not require any modifications inside django_fsm.transition. The `this.is_happy` call will return callable like `lambda m: getattr(m, 'is_happy)'`

**Comment by karyon** [comment]
while it's technically cool, that would introduce something that is unpythonic AND totally unlike django :) i would very much prefer to be in line with django and do it with strings. if you don't want that, i'd probably take the lambdas.

**Comment by kmmbvnr** [comment]
The core problem of strings is that the single function parameter became accepts 2 types of arguments - strings and lambdas.

I don't like to introduce such ambiguity. And it can't be considered as django way, b/c django use strings on consistent maneur and only for field references, not for properties or methods.
