### ISSUE TITLE
shortcut to specify transitions from all states except the target

### ISSUE THREAD

**Issue by seddonym** [kmmbvnr/django-fsm#97]
Currently the `*` shortcut can be used to specify that a transition can happen from any state.

It would be great if there was a simple shortcut that allowed a transition from any state except the target.  For example, if I have a state called 'Publish' then it doesn't make sense to transition from 'Publish' to 'Publish'.

Possible syntax:
   
    from django_fsm import ALL_BUT_TARGET

    @transition(field=state, source=ALL_BUT_TARGET, target='published')
    def publish(self):
        pass

**Comment by kmmbvnr** [comment]
Yep, that's good addition. Currently i'm using `conditions=[lambda o: o.state != 'published']` to prevent such transition. I think just '+' would be enough for the shortcut name.

     @transition(field=state, source='+', target='published')
     def publish(self):
          pass

Pull requests are welcome

**Comment by seddonym** [comment]
Oh that's nice I hadn't thought of using the `conditions` argument like that.  If I get a chance I'll do a pull request at some point!

**Comment by seddonym** [comment]
Great!  Thanks.
